#!/usr/bin/env python3
"""Generate the small CJK bitmap subset used by the Focus AIoT UI."""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

SIZE = 14
CHARS = """待机长按开始键进入模式选择学习严格鼓励监督温暖陪伴切换确认有效分心次专注度已分钟报告总时明细玩手机看离座瞌睡良好建议获取中返回请回到位放下注意坐姿休息了就继续吧等你来哦要不要起来活动一下今天坚持减少会更棒加油完成稍后查看详细加载失败重新做得很优秀合格保持下次里程碑小时"""


def unique_chars(text: str) -> list[str]:
    return list(dict.fromkeys(ch for ch in text if not ch.isspace()))


def glyph_rows(font: ImageFont.FreeTypeFont, char: str) -> list[int]:
    image = Image.new("1", (SIZE, SIZE), 0)
    draw = ImageDraw.Draw(image)
    bbox = draw.textbbox((0, 0), char, font=font)
    width = bbox[2] - bbox[0]
    height = bbox[3] - bbox[1]
    x = (SIZE - width) // 2 - bbox[0]
    y = (SIZE - height) // 2 - bbox[1]
    draw.text((x, y), char, font=font, fill=1)
    rows = []
    for row in range(SIZE):
        bits = 0
        for col in range(SIZE):
            if image.getpixel((col, row)):
                bits |= 1 << (SIZE - 1 - col)
        rows.append(bits)
    return rows


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    font_path = Path(r"C:\Windows\Fonts\NotoSansSC-VF.ttf")
    output = repo / "app" / "hello_app" / "ui" / "ui_cjk_font.c"
    font = ImageFont.truetype(str(font_path), SIZE)
    entries = []
    for char in unique_chars(CHARS):
        entries.append((ord(char), glyph_rows(font, char), char))
    entries.sort(key=lambda item: item[0])

    lines = [
        "/* Generated by tools/generate_ui_cjk_font.py from Noto Sans SC. */",
        '#include "ui_cjk_font.h"',
        "",
        "#include <stddef.h>",
        "",
        "struct ui_cjk_entry_s",
        "{",
        "  uint32_t codepoint;",
        "  uint16_t rows[UI_CJK_GLYPH_SIZE];",
        "};",
        "",
        "static const struct ui_cjk_entry_s g_cjk_glyphs[] =",
        "{",
    ]
    for codepoint, rows, char in entries:
        row_text = ", ".join(f"0x{row:04x}" for row in rows)
        lines.append(f"  {{0x{codepoint:04x}, {{{row_text}}}}}, /* {char} */")
    lines.extend(
        [
            "};",
            "",
            "const uint16_t *ui_cjk_glyph(uint32_t codepoint)",
            "{",
            "  size_t low = 0;",
            "  size_t high = sizeof(g_cjk_glyphs) / sizeof(g_cjk_glyphs[0]);",
            "  while (low < high)",
            "    {",
            "      size_t middle = low + (high - low) / 2;",
            "      if (g_cjk_glyphs[middle].codepoint < codepoint)",
            "        low = middle + 1;",
            "      else",
            "        high = middle;",
            "    }",
            "  if (low < sizeof(g_cjk_glyphs) / sizeof(g_cjk_glyphs[0]) &&",
            "      g_cjk_glyphs[low].codepoint == codepoint)",
            "    return g_cjk_glyphs[low].rows;",
            "  return NULL;",
            "}",
            "",
        ]
    )
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
